jobs:
  - name: J1
    type: runSh
    allowPublicAccess: true
    steps:
      - IN: R1
        switch: off
      - TASK:
        - script: echo "Sleeping..." && sleep 20
        - script: echo "Hello, World!"

  - name: J2
    type: runSh
    steps:
      - IN: R1
      - TASK:
        - script: echo "Sleeping..." && sleep 20
        - script: echo "Hello, World!"

  - name: J3
    type: runSh
    steps:
      - IN: R1
      - TASK:
        #- script: exit 128
        - script: echo "Sleeping..." && sleep 20
        - script: echo "Hello, World!"

  - name: J4
    type: runSh
    steps:
      - IN: J1
      - IN: J2
      - IN: J3
      - TASK:
        - script: echo "Hello, World!"


  - name: J5
    type: runSh
    steps:
      - IN: J4
      - TASK:
        - script: echo "Hello, World!"

  - name: J6
    type: runSh
    steps:
      - IN: J4
      - TASK:
        - script: echo "Hello, World!"

  - name: J7
    type: runSh
    steps:
      - IN: J5
      - IN: J6
      - TASK:
        - script: echo "Hello, World!"

  - name: J8
    type: runSh
    steps:
      - IN: J7
      - TASK:
        - script: echo "Hello, World!"

  - name: J9
    type: runSh
    steps:
      - IN: J7
      - TASK:
        - script: echo "Hello, World!"
        
  - name: J10
    type: runSh
    steps:
      - IN: J7
      - TASK:
        - script: echo "Hello, World!"
        
  - name: J11
    type: runSh
    steps:
      - IN: J7
      - TASK:
        - script: echo "Hello, World!"
        
  - name: J12
    type: runSh
    steps:
      - IN: J7
      - TASK:
        - script: echo "Hello, World!"
        
  - name: J13
    type: runSh
    steps:
      - IN: J7
      - TASK:
        - script: echo "Hello, World!"
        
  - name: J14
    type: runSh
    steps:
      - IN: J7
      - TASK:
        - script: echo "Hello, World!"
        
  - name: J15
    type: runSh
    steps:
      - IN: J7
      - TASK:
        - script: echo "Hello, World!"
        
  - name: J16
    type: runSh
    steps:
      - IN: J7
      - TASK:
        - script: echo "Hello, World!"
        
  - name: J17
    type: runSh
    steps:
      - IN: J7
      - TASK:
        - script: echo "Hello, World!"
        
  - name: J18
    type: runSh
    steps:
      - IN: J7
      - TASK:
        - script: echo "Hello, World!"
        
  - name: J19
    type: runSh
    steps:
      - IN: J7
      - TASK:
        - script: echo "Hello, World!"
        
  - name: J20
    type: runSh
    steps:
      - IN: J7
      - TASK:
        - script: echo "Hello, World!"
        
  - name: J21
    type: runSh
    steps:
      - IN: J7
      - TASK:
        - script: echo "Hello, World!"
        
  - name: J22
    type: runSh
    steps:
      - IN: J7
      - TASK:
        - script: echo "Hello, World!"
        
  - name: J23
    type: runSh
    steps:
      - IN: J7
      - TASK:
        - script: echo "Hello, World!"
        
  - name: J24
    type: runSh
    steps:
      - IN: J7
      - TASK:
        - script: echo "Hello, World!"
        
  - name: J25
    type: runSh
    steps:
      - IN: J7
      - TASK:
        - script: echo "Hello, World!"
